$pilot = "2015/11/15"
$region1 = "2015/11/22" # One week after pilot
$region2 = "2015/11/23" # One day after
$cdb = "2015/11/24"     # One day after
$all = "2015/11/29"     # Sunday after
$reboot = "2015/12/3"   # Thursday after

Start-CMSoftwareUpdateDeployment -CollectionName "Workstation - 2 - Pilot" -SoftwareUpdateGroupName "Workstation - Monthly" -DeploymentAvailableDay $pilot -DeploymentAvailableTime 19:00:00 -DeploymentName "Workstation - 2 - Pilot - Monthly" -DeploymentType Required -EnforcementDeadline 19:00 -EnforcementDeadlineDay $pilot -PersistOnWriteFilterDevice $True -RestartServer $True -RestartWorkstation $True -SendWakeupPacket $True -TimeBasedOn LocalTime -UseBranchCache $True -UserNotification DisplayAll -VerbosityLevel OnlySuccessAndErrorMessages
Start-CMSoftwareUpdateDeployment -CollectionName "Workstation - 3 - Regional - Primary" -SoftwareUpdateGroupName "Workstation - Monthly" -DeploymentAvailableDay $region1 -DeploymentAvailableTime 19:00:00 -DeploymentName "Workstation - 3 - Regional - Primary - Monthly" -DeploymentType Required -EnforcementDeadline 19:00 -EnforcementDeadlineDay $region1 -PersistOnWriteFilterDevice $True -RestartServer $True -RestartWorkstation $True -SendWakeupPacket $True -TimeBasedOn LocalTime -UseBranchCache $True -UserNotification DisplayAll -VerbosityLevel OnlySuccessAndErrorMessages
Start-CMSoftwareUpdateDeployment -CollectionName "Workstation - 4 - Regional - Secondary" -SoftwareUpdateGroupName "Workstation - Monthly" -DeploymentAvailableDay $region2 -DeploymentAvailableTime 19:00:00 -DeploymentName "Workstation - 4 - Regional - Secondary - Monthly" -DeploymentType Required -EnforcementDeadline 19:00 -EnforcementDeadlineDay $region2 -PersistOnWriteFilterDevice $True -RestartServer $True -RestartWorkstation $True -SendWakeupPacket $True -TimeBasedOn LocalTime -UseBranchCache $True -UserNotification DisplayAll -VerbosityLevel OnlySuccessAndErrorMessages
Start-CMSoftwareUpdateDeployment -CollectionName "Workstation - 5 - CBD - Primary" -SoftwareUpdateGroupName "Workstation - Monthly" -DeploymentAvailableDay $cdb -DeploymentAvailableTime 19:00 -DeploymentName "Workstation - 5 - CBD - Primary - Monthly" -DeploymentType Required -EnforcementDeadline 19:00 -EnforcementDeadlineDay $cdb -PersistOnWriteFilterDevice $True -RestartServer $True -RestartWorkstation $True -SendWakeupPacket $True -TimeBasedOn LocalTime -UseBranchCache $True -UserNotification DisplayAll -VerbosityLevel OnlySuccessAndErrorMessages
Start-CMSoftwareUpdateDeployment -CollectionName "All Workstations" -SoftwareUpdateGroupName "Workstation - Monthly" -DeploymentAvailableDay $all -DeploymentAvailableTime 19:00 -DeploymentName "Workstation - 6 - All Workstations - Monthly" -DeploymentType Required -EnforcementDeadline 19:00 -EnforcementDeadlineDay $reboot -PersistOnWriteFilterDevice $True -RestartServer $True -RestartWorkstation $False -SendWakeupPacket $True -TimeBasedOn LocalTime -UseBranchCache $True -UserNotification DisplayAll -VerbosityLevel OnlySuccessAndErrorMessages